### ISSUE TITLE
Install latest version: why not offering a "ready to use" zip file?

### ISSUE THREAD

**Issue by laclaro** [Ericsson/exchangecalendar#241]
Hi,

I don't understand the nesseccary of the recompressing step with the latest addon. Why don't you offer a zip file that is already compressed without the additional subfolder?

https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

Best regards,
Henning

**Comment by bavincen** [comment]
Its a git hub offering. 
let us know if we can do that..

**Comment by awilkins** [comment]
The instructions are just exploiting the standard Github feature of a zipped download of the source tree - since the plugin is all uncompiled script, you don't need to do anything but repack it, because the Mozilla engine expects the file structure to be a certain way - without the top level folder.

Putting a top level folder in archives is considered polite in the *nix community because that way you can just unthinkingly unpack them and not spam up your current folder with a shower of loose files.

If you have an archive program on your path (e.g. 7-zip)

    unzip exchangecalender-master.zip && cd exchangecalendar-master && 7zip a ../ews.zip * && mv ../ews.zip ../ews.xpi

.. is not such a chore

**Comment by bavincen** [comment]
i guess we can add your note to wiki
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

**Comment by bavincen** [comment]
Thanks for suggesting. Its not with us.
