### ISSUE TITLE
User can accept meeting from Right side "Event and Task" Section and as well from email body. The accpet email go twice time.

### ISSUE THREAD

**Issue by vikas290691** [Ericsson/exchangecalendar#263]
Steps to Rreproduce:

1. First get a calendar event and try to accept it from "Event and Task" section.
2. Open the event and accept it.
3. Send the email response.
4. Check the email in sent items. Event should be accepted.
5. Now Check the inobx now, you can will still the see accept button on email body.
5. You will be able to accept the event and will be able to send the response still.

Issue:
Expectedly, It should not happen. If you had accepted a calendar event once, then accepting a event again option should not be there.

**Comment by kiravi** [comment]
Seems to be a TBird issue.  

Typically if you are directly connected to exchange all accept is from inbox on outlook, which also deletes the invite.  

This is happening, so preferably do it from inbox?  Also these show up with the invitation link below on TBird UI, even that works well.  

Perhaps this is a lightning issue, and it should be fixed in events/tasks by automatically deleting the inbox message.

**Comment by bavincen** [comment]
Yes this issue is in lightning. Please raise one in lightning
