### ISSUE TITLE
Event reminder pop-up doesn't appear when reminder time has up and then we start the thudnerbird.

### ISSUE THREAD

**Issue by vikas290691** [Ericsson/exchangecalendar#264]
Steps to reproduce:
1. get a calendar event , suppose timings are (12:30 PM to 03:00 PM).
2. Check the reminder before raising it. (lets suppose it is 15 minutes).
3. Now Close the Thunderbird before 12:15 PM or before reminder pop-up comes.
4. Now Start the thunderbird, around 12:20 PM or 12:25 PM anytime.
5. Expected behavior, pop-up should come for your calendar event which occurs on 12:30 PM.

Issue: The expected behavior is not there. we are not seeing any pop-up for that. it seems , it doesn't show that pop-up because reminder time was 15 minutes which has gone when we start the thunderbird.

**Comment by bavincen** [comment]
@muthusuba This reminder window does not pop up after first snooze time if the user doesn’t use TB at the same time.

**Comment by Mats1st** [comment]
Some additional things which may belong together:
I can't confirm or close a past (recurring) appointment or it pops up again and again. One thing will break the circle: right click on the calendar name in the left hand sides calendar list --> "Exchange (EWS) properties" --> choose "Offline Caching" card --> click the button "delete Offline-Cache"
Maybe the Addon should delete the cache by its own from time to time (after wake up the pc from hibernate and stand-by) ...
Notice: In 3.4~beta 4 the EWS properties window will not open! Please check to confirm. (Maybe a little mistake in program code) - That's why I switches back to beta 1.

**Comment by bavincen** [comment]
@Mats1st closing snooze the event.. actually you have to dismiss past events

**Comment by bavincen** [comment]
fyi using beta1 u may face different  reminder issues

**Comment by bavincen** [comment]
It's not happeningwith beta 5 closing it

**Comment by Mats1st** [comment]
After a while of watching, I can confirm fixing this issues in beta 5!

**Comment by Mats1st** [comment]
It seams a nearly similar issue has come with 3.4.0 RC1...
My continuous event in my calendar can't be confirmed or closed. The pop-up closes after clicking on confirm or close button but it pops up promptly again.
This issue is only a problem on continuous events and do not happen on one-time events.

**Comment by bavincen** [comment]
Just closing will not dismiss or snooze

**Comment by Mats1st** [comment]
I have no further options... I can click the 'close' button behind the event; I can click the red cross of the window; I can click on the button 'close all' on bottom of the window; In all cases I get the same result: The pop-up closes and rises again...

**Comment by bavincen** [comment]
what i meant before is You have no option to disable popup until you snooze or dismiss
