### ISSUE TITLE
Autodiscovery does not work

### ISSUE THREAD

**Issue by bueste** [Ericsson/exchangecalendar#391]
Hi
I've tested the beta plugin. The autodiscovery does not work. 
I've tested with other applications, no problem.
Pls fix it. Thx a lot
Stefan

**Comment by Trim** [comment]
Hello,

Could you share with us the autodiscovery configuration of your server ?

According to [Microsoft](https://msdn.microsoft.com/en-us/library/office/jj900169%28v=exchg.150%29.aspx), there's multiple ways to specify autodiscovery.

If I've read correctly the exchangecalendar plugin code, it can find configuration only with the POX way.
Indeed, the plugin send a POST request to possible autodiscovery addresses with [this XML content](https://msdn.microsoft.com/en-us/library/office/bb204189%28v=exchg.150%29.aspx).

The XML part is relatively easy to create with Thunderbird tools, so I think that's why other autodiscover methods aren't applied currently.

**Comment by bavincen** [comment]
You have to enter correct domain name,email and username before clicking autodiscovery button
