### ISSUE TITLE
Can't connect to Exchange server with TB 52.1.1 and Lightning 5.4

### ISSUE THREAD

**Issue by obfuscoder** [Ericsson/exchangecalendar#594]
Today I updated to Thunderbird 52.1.1 and Lightning 5.4. With this the exchange calendar went blank. The log file showed some 401 Unauthorized responses from the exchange server.

When I openend the Exchange (EWS) properties of the Exchange calendar, changed my username to something else then back to the original one and hit *Check server mailbox* in between, I get the error message:

```
Error during checking of server and mailbox: HTTP Client error 401: Unauthorized
URL:https://owa.extranet.1and1.org/ews/exchange.asmx

 (Code: -19)
```
The program does not ask for the password.

Enabling plain text password logging shows that the stored password for my account is correct.

**Comment by martijndevrieze** [comment]
Having the same issue with a new install of Arch Linux. Thunderbird with Lightning and EWS used to work like a charm, I cannot get the calendar to work now. 

Log file: 

1st-setup:2017-4-3 9:46:1.781:mivExchangeAuthPrompt2: getPassword: There is no password stored in the passwordManager. (_getPassword in mivExchangeAuthPrompt2.js:159)
1st-setup:2017-4-3 9:46:1.781:mivExchangeAuthPrompt2: getPassword: password(2)=******** (_getPassword in mivExchangeAuthPrompt2.js:166)
1st-setup:2017-4-3 9:46:1.781:mivExchangeAuthPrompt2: getPassword: First request for a password. Not going to ask user for it because we want to see if we need a password. For Kerberos for example we do not need a password. (_getPassword in mivExchangeAuthPrompt2.js:205)
1st-setup:2017-4-3 9:46:1.782:16208bbd-c069-4274-a6d1-4691c46393db: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2017-4-3 9:46:1.782:16208bbd-c069-4274-a6d1-4691c46393db: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2017-4-3 9:46:1.783:16208bbd-c069-4274-a6d1-4691c46393db: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2017-4-3 9:46:1.783:16208bbd-c069-4274-a6d1-4691c46393db: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2017-4-3 9:46:1.783:16208bbd-c069-4274-a6d1-4691c46393db: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2017-4-3 9:46:1.783:16208bbd-c069-4274-a6d1-4691c46393db: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2017-4-3 9:46:1.783:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({70d2b4fe-a552-48cd-8d93-1d8437a56b53})
1st-setup:2017-4-3 9:46:1.783:16208bbd-c069-4274-a6d1-4691c46393db: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2017-4-3 9:46:1.784:16208bbd-c069-4274-a6d1-4691c46393db: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2017-4-3 9:46:1.784:16208bbd-c069-4274-a6d1-4691c46393db: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2017-4-3 9:46:1.784:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({1040ebe3-6ed1-45a6-8587-995e082518d7})
1st-setup:2017-4-3 9:46:1.784:16208bbd-c069-4274-a6d1-4691c46393db: ecnsIAuthPrompt2.getInterface: Ci.nsIApplicationCacheContainer
1st-setup:2017-4-3 9:46:1.785:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2017-4-3 9:46:1.785:16208bbd-c069-4274-a6d1-4691c46393db: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2017-4-3 9:46:1.788:16208bbd-c069-4274-a6d1-4691c46393db: ecnsIAuthPrompt2.getInterface: Ci.nsIProgressEventSink
1st-setup:2017-4-3 9:46:1.788:16208bbd-c069-4274-a6d1-4691c46393db:   --- ecnsIAuthPrompt2.onStatus: STATUS_SENDING_TO of outlook.office365.com
1st-setup:2017-4-3 9:46:1.788:16208bbd-c069-4274-a6d1-4691c46393db:   --- ecnsIAuthPrompt2.onProgress: this is a nsIChannel
1st-setup:2017-4-3 9:46:1.788:16208bbd-c069-4274-a6d1-4691c46393db:   --- ecnsIAuthPrompt2.onProgress:2606 of 2606
1st-setup:2017-4-3 9:46:1.789:16208bbd-c069-4274-a6d1-4691c46393db:   --- ecnsIAuthPrompt2.onStatus: STATUS_WAITING_FOR of outlook.office365.com
1st-setup:2017-4-3 9:46:1.825:16208bbd-c069-4274-a6d1-4691c46393db: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2017-4-3 9:46:1.825:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2017-4-3 9:46:1.826:16208bbd-c069-4274-a6d1-4691c46393db:   --- ecnsIAuthPrompt2.onStatus: STATUS_SENDING_TO of outlook.office365.com
1st-setup:2017-4-3 9:46:1.826:16208bbd-c069-4274-a6d1-4691c46393db:   --- ecnsIAuthPrompt2.onProgress: this is a nsIChannel
1st-setup:2017-4-3 9:46:1.826:16208bbd-c069-4274-a6d1-4691c46393db:   --- ecnsIAuthPrompt2.onProgress:2669 of 2669
1st-setup:2017-4-3 9:46:1.826:16208bbd-c069-4274-a6d1-4691c46393db:   --- ecnsIAuthPrompt2.onStatus: STATUS_WAITING_FOR of outlook.office365.com
1st-setup:2017-4-3 9:46:7.16:16208bbd-c069-4274-a6d1-4691c46393db: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2017-4-3 9:46:7.17:exchWebServicesCheckServerAndMailboxError: aCode:-19, aMsg:HTTP Client error 401: Unauthorized

**Comment by janickm** [comment]
Seems to be the same issue of #580 addressed in !592 ?

**Comment by obfuscoder** [comment]
Yes you are right. I missed to check the already existing issue. Closing as duplicate of #580
