### ISSUE TITLE
thunderbird says the files are corrupt

### ISSUE THREAD

**Issue by ghost** [Ericsson/exchangecalendar#637]
Tried many versions from 3.9.0 beta 2 back to 3.7.0.  I have verified the checksum after downloading.  But when I try to install add on as file thunderbird says it cannot be installed because it appears to be corrupt  I am using Thunderbird 78.6.0 on Windows 10.

**Comment by Mechtilde** [comment]
Hello,

exchangecalendar isn't supported anymore.

there is no update to use as web-extension since thunderbid 78.x

At his place you can use

https://github.com/jobisoft/TbSync

which is also available at
https://addons.thunderbird.net/de/thunderbird/addon/tbsync/

and packaged for Debian and Ubuntu

Kind regards

Am 29.12.20 um 17:14 schrieb chjopf:
> Tried many versions from 3.9.0 beta 2 back to 3.7.0.  I have verified the checksum after downloading.  But when I try to install add on as file thunderbird says it cannot be installed because it appears to be corrupt  I am using Thunderbird 78.6.0 on Windows 10.
> 

-- 
Mechtilde Stehmann

## Debian Developer
## PGP encryption welcome
## F0E3 7F3D C87A 4998 2899  39E7 F287 7BBA 141A AD7F

**Comment by minecraftchest1** [comment]
If this is the case, please mark the repro as archived, and/or mention that it is unsupported in the README.
